package marketdata

// TRADITION USD quotes for curve date 2025-10-31.
// Generated by generate_fixtures.py on 2025-12-04 10:57:33
var (
	// SOFR OIS curve (19 tenors)
	TRADITIONSofr = map[string]float64{
		"6M":  2.215,
		"9M":  2.175,
		"1Y":  2.195,
		"18M": 2.2,
		"2Y":  2.22,
		"3Y":  2.305,
		"4Y":  2.36,
		"5Y":  2.42,
		"6Y":  2.41,
		"7Y":  2.39,
		"8Y":  2.355,
		"9Y":  2.32,
		"10Y": 2.31,
		"11Y": 2.3,
		"12Y": 2.3,
		"15Y": 2.295,
		"20Y": 2.23,
		"25Y": 2.08,
		"30Y": 1.91,
	}
)
