package data

// BGN JPY quotes for curve date 2025-12-10.
// Generated by generate_fixtures.py on 2025-12-12 18:41:31
var (
	// TONAR OIS curve (34 tenors)
	BGNTonar = map[string]float64{
			"1W": 0.4775,
			"2W": 0.54375,
			"1M": 0.632575,
			"2M": 0.669975,
			"3M": 0.684175,
			"4M": 0.696865,
			"5M": 0.709345,
			"6M": 0.72325,
			"7M": 0.746,
			"8M": 0.757635,
			"9M": 0.781,
			"10M": 0.79475,
			"11M": 0.81275,
			"1Y": 0.8325,
			"15M": 0.88841,
			"18M": 0.9465,
			"21M": 1.00125,
			"2Y": 1.05125,
			"3Y": 1.19625,
			"4Y": 1.2975,
			"5Y": 1.37625,
			"6Y": 1.45125,
			"7Y": 1.52875,
			"8Y": 1.602,
			"9Y": 1.6775,
			"10Y": 1.75625,
			"11Y": 1.8355,
			"12Y": 1.91375,
			"15Y": 2.14125,
			"20Y": 2.463,
			"25Y": 2.664,
			"30Y": 2.78,
			"35Y": 2.855,
			"40Y": 2.899,
	}

	// TIBOR3M curve (18 tenors)
	BGNTibor3M = map[string]float64{
			"3M": 0.98273,
			"1Y": 1.17,
			"18M": 1.2965,
			"2Y": 1.40875,
			"3Y": 1.57375,
			"4Y": 1.695,
			"5Y": 1.79125,
			"6Y": 1.88125,
			"7Y": 1.9725,
			"8Y": 2.0595,
			"9Y": 2.14625,
			"10Y": 2.23625,
			"12Y": 2.40375,
			"15Y": 2.635,
			"20Y": 2.95925,
			"25Y": 3.16275,
			"30Y": 3.27875,
			"40Y": 3.39775,
	}

	// TIBOR6M curve (19 tenors)
	BGNTibor6M = map[string]float64{
			"6M": 0.96091,
			"1Y": 1.135,
			"18M": 1.2615,
			"2Y": 1.37875,
			"3Y": 1.545,
			"4Y": 1.66625,
			"5Y": 1.7625,
			"6Y": 1.855,
			"7Y": 1.94875,
			"8Y": 2.0395,
			"9Y": 2.13125,
			"10Y": 2.225,
			"12Y": 2.3975,
			"15Y": 2.63375,
			"20Y": 2.97675,
			"25Y": 3.179,
			"30Y": 3.295,
			"35Y": 3.37,
			"40Y": 3.414,
	}
)

// Aliases for BGNS-style naming when TONAR is from BGN and TIBOR is from BGNS.
// These allow code to refer to BGNSTibor3M/BGNSTibor6M while using the mixed-source fixtures here.
var (
	BGNSTibor3M = BGNTibor3M
	BGNSTibor6M = BGNTibor6M
)
